### PR TITLE
Decode JSON in single line

### PR DESCRIPTION
**Pull request by romanyx**
Hi, here's a small change.

### CODE REVIEW

**Comment by matryer** [comment]
Thanks for your PR. I prefer calling Marshal directly as it incurs fewer allocations, and since we only expect one JSON object/array to be in the request (rather than reading a stream of them) I think the code is good as it stands. What do you think?

**Comment by romanyx** [comment]
I disagree, here're a benchmark:

```bash
Decode       1000000	      1168 ns/op     1048 B/op	       6 allocs/op
Unmarshal  1000000	      1694 ns/op     2496 B/op	       7 allocs/op
```

https://play.golang.org/p/4D9HQs6qlYs

**Comment by matryer** [comment]
Well I'm not going to argue with that.

**Comment by matryer** [comment]
Thanks @romanyx 👍

**Pull request merged**
